{{- if .Values.cognito.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "superset.fullname" . }}-cognito
  namespace: {{ include "base.namespace" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.cognito.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ template "superset.fullname" . }}-cognito-env
    creationPolicy: Owner
  data:
    - secretKey: COGNITO_CLIENT_ID
      remoteRef:
        key: {{ .Values.cognito.secretArn }}
        property: COGNITO_CLIENT_ID
    - secretKey: COGNITO_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.cognito.secretArn }}
        property: COGNITO_CLIENT_SECRET
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.cognito.secretArn }}
        property: SUPERSET_DB_USER
    - secretKey: DB_PASS
      remoteRef:
        key: {{ .Values.cognito.secretArn }}
        property: SUPERSET_DB_PASS
{{- end }}
